models/post.py
from typing import Optional
from datetime import datetime
from sqlmodel import Field, SQLModel


class Post(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    title: str
    content: str
    publish_date: datetime = Field(default_factory=datetime.today)

app.py
from flask import Flask, render_template, request, flash, redirect, url_for
from routes.post import post_pages
from sqlmodel import SQLModel, create_engine
from models.post import Post


      
app = Flask(__name__, static_folder='static')
app.engine = create_engine("sqlite:///database.db") 
 
@app.route('/')
def home():
    return render_template('home.html')

@app.route('/about')
def about():
    return render_template('about.html')


        

@app.before_request
def create_db():
    SQLModel.metadata.create_all(app.engine)


app.register_blueprint(post_pages)

if __name__ == '__main__':
    app.run(debug=True)

routes/about.py
from flask import Flask, render_template
from app import app

@app.route('/about')
def about():
    return render_template('about.html')

routes/post.py
from flask import Blueprint, current_app, request, render_template, redirect, url_for
from sqlmodel import Session, select
from models.post import Post

post_pages = Blueprint("posts", __name__)

@post_pages.get('/post/<string:title>')
def display_post(title: str):
    with Session(current_app.engine) as session:
        statement = select(Post).where(Post.title == title)
        post = session.exec(statement).first()
    return render_template("post.html", title=title, content=post.content)

@post_pages.route("/post/", methods=["GET", "POST"])
def create_post():
    if request.method == "POST":
        title = request.form.get("title")
        content = request.form.get("content")
        with Session(current_app.engine) as session:
            session.add(Post(title=title, content=content))
            session.commit()
        return redirect(url_for(".display_post", title=title))
    return render_template("new_post.html")


templates/about.html
<!DOCTYPE html>
<html>
<lang = 'en'>
    <head>
        <title>About</title>
        <link rel="stylesheet" href="{{url_for('static', filename='css/style4.css')}}">
    </head>
    <body>
    <h1>About Me</h1>
    <p>I am a 31 year old fitness enthusiast looking to share my knowledge with others!</p>
    </body>
    </html>



templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
</head>
    <body>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="{{url_for('routes', filename='about.html')}}">About</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
        <h1>Chris's Blog</h1>
        <p>Welcome to my fitness and lifesyle blog!</p>
        <br>
        <div class="grid">
            <img src="https://images.pexels.com/photos/791763/pexels-photo-791763.jpeg?cs=srgb&dl=black-and-white-man-person-791763.jpg&fm=jpg" width="450" height="300">
            <img src="https://www.stockvault.net/data/2008/11/11/106597/preview16.jpg">
          </div>
        <br>
        <a href="{{ url_for('posts.create_post') }}" class="link">Go to Post Page</a>
    </body>
</html>


templates/new_post.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=devoce-width, intial-scale=1.0">
        <title>New Post</title>
        <link rel="stylesheet" href="{{url_for('static', filename='css/style2.css')}}">
    </head>
    <body>
        <h1>Make a New Post</h1>
        <form method="POST">
            <label for="title">Title:</label>
            <input type="text" name="title"id="title"/>

            <label for="content">Content: </label>
            <textarea name="content" id="content"></textarea>

            <input type="submit" value="Create post"/>
        </form>
    </body>
    </html>

templates/post.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style3.css')}}">
</head>
<body>
    <article>
        <h1>{{ title }}</h1>
        <p>{{ content }}</p>
    </article>
</body>
</html>